apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: idyh4rhnd-python
  janus-idp.io/tekton: idyh4rhnd-python
  backstage.io/kubernetes-id: idyh4rhnd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: idyh4rhnd-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
