apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: idyh4rhnd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: idyh4rhnd-python 
  name: idyh4rhnd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: idyh4rhnd-python 
