apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: idyh4rhnd-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-743045c910.8364.p3.openshiftapps.com/rhtap/rhtap-qe-python:5b8d20e8b8e99fdef552ba8e855081c4f88a3e23@sha256:5bb6ae495cb8ba34bdf49657162c8083dd3c94a2bdadd222bc487bd1bbafb387
          name: container-image
